version: '3.8'

services:
  ai-gateway:
    # Build yerine Hub image kullan (production için)
    image: sadikhanecioglu/ai-gateway:latest
    container_name: ai-gateway
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
    env_file:
      - .env.production  # Production environment file
    volumes:
      - ./credentials/service-account.json:/app/credentials/service-account.json:ro
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - ai-gateway-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  
networks:
  ai-gateway-network:
    driver: bridge

volumes:
  logs: